services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Stsbl\HostConfigBundle\:
        resource: '../../'
        exclude: '../../{Entity,Resources,Tests}'

    Stsbl\HostConfigBundle\FieldDefinition\FieldDefinitionLoader:
        bind:
            $directories: ['/usr/share/iserv/shared/host-config/fields', '/etc/iserv/host-config/fields']
